### ISSUE TITLE
imposible to start jam.py

### ISSUE THREAD

**Issue by fe8769a** [jhonnybonny/CleverJAM#3]
imposible to start jam.py

here is the result

python3 jam.py                             <main ✗>
/home/cpi/Documents/CleverJAM/jam.py:5: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
  from distutils.version import StrictVersion
Traceback (most recent call last):
  File "/home/cpi/Documents/CleverJAM/jam.py", line 274, in <module>
    main()
  File "/home/cpi/Documents/CleverJAM/jam.py", line 252, in main
    tb = top_block_cls()
  File "/home/cpi/Documents/CleverJAM/jam.py", line 41, in __init__
    gr.top_block.__init__(self, "Jammer Gen")
  File "/usr/local/lib/python3.10/dist-packages/gnuradio/gr/top_block.py", line 96, in __init__
    hier_block2.__init__(self, name, None, None, top_block_pb(name, catch_exceptions))
ValueError: pmt_dcons: not a dict: wrong_type #<unknown>
double free or corruption (!prev)
[1]    143204 abort      python3 jam.py

no idea on how to solve .Thanks for help

**Comment by alphafox02** [comment]
It’s included in and working in DragonOS. I did a video about it awhile back. Not sure what setup you’re running, but maybe do a comparison.

**Comment by fe8769a** [comment]
I'm able to run under dragon os. I tried to install on clock pi computer. I
have to reinstall all gnaradio libraries for this laptop. This clock pi
based on arm can't run dragon os raspi. I have maybe some python 3 not
working
