### ISSUE TITLE
Possibility to jam dual band WiFi (2,4G/5G)

### ISSUE THREAD

**Issue by pn3m0n1c** [jhonnybonny/CleverJAM#4]
Hi! I used this jammer and it works nicely with HackRF One, but when I am trying to jam a access point with both bands 2,4GHz and 5GHz, it does not work, maybe because when I am trying to connect with my phone for instance, the 5G signal is inhibited but not the 2.4G so the phone quickly changes. It is possible make adjustments to emit noise with only one device for both bands?

**Comment by jhonnybonny** [comment]
U need write all bands in config 

Not like 2.5 5.0 
U need write each channel on wifi because hackrf use 20mhz bandwidth its to small...

**Comment by jhonnybonny** [comment]
Also if u need jam all bands 5-4-3g 
Use modmobjam for this
